# ===============================
# Step 1: Installing dependencies
# ===============================
FROM node:22-alpine AS dependencies 

WORKDIR /app

COPY package*.json ./

RUN npm ci

# ===============================
# Step 2: Build
# ===============================
FROM node:22-alpine AS builder

WORKDIR /app

COPY --from=dependencies /app/node_modules ./node_modules

COPY . .

RUN npm run build

# ===============================
# Step 3: production
# ===============================
FROM node:22-alpine AS production

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 8000

CMD ["node", "dist/main.js"]