upstream frontend_upstream {
    server devop-nuxt-prod:3000;
}
upstream backend_upstream {
    server devop-nest-prod:8000;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 50M;

    # =================================
    # Frontend - NuxtJS API
    # =================================
    location / {
        proxy_pass http://frontend_upstream;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
        proxy_send_timeout 60s;

    }

    # =================================
    # Backend - NestJS API
    # =================================
    location /api/ {
        proxy_pass http://backend_upstream;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
        proxy_send_timeout 60s;
    }

    # =================================
    # Basic security headers
    # =================================
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

}



